language: python
python:
  - "3.8"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: 
  - psql -c 'create database testdb;' -U postgres

# script:
#   - nosetests

after_success:
  - codecov

services:
  - postgresql

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# command to run tests
jobs:
  include:
    - stage: Test
      name: TDD
      script: nosetests

    - stage: Test
      name: BDD
      addons:
        chrome: stable
        apt:
          packages:
            # - chromium-chromedriver
            - python3-selenium
      before_script:
        - chromedriver --version
        - gunicorn --log-level=critical --bind=127.0.0.1:5000 service:app &  # start a Web server in the background
        - sleep 5 # give Web server some time to bind to sockets, etc
        - curl -I http://localhost:5000/  # make sure the service is up
      script:
        - behave